dist: xenial
language: python

cache: pip

python:
    - "3.5"
    - "3.6"
    - "3.7"
    - "3.8-dev"

addons:
    postgresql: "9.5"

services:
  - postgresql

install:
    - pip install -U -r requirements.txt
    - pip install -U -r requirements_dev.txt

script:
    - scripts/test

after_script:
    - pip install codecov
    - codecov
